### ISSUE TITLE
msg="AutoDiscovery stopped: ProtocolDiscovery not implemented

### ISSUE THREAD

**Issue by sawashar** [edgexfoundry/device-opc-ua#15]
Hi,
After Running the opcua-go service and the prosys simulation server for opcua Iam getting following logs:
level=INFO ts=2022-01-27T11:00:04.56535565Z app=device-opcua source=config.go:373 msg="Loaded service configuration from ./res/configuration.toml"
level=INFO ts=2022-01-27T11:00:04.567181102Z app=device-opcua source=config.go:510 msg="Using local configuration from file (0 envVars overrides applied)"
level=INFO ts=2022-01-27T11:00:04.567592323Z app=device-opcua source=httpserver.go:123 msg="Web server starting (localhost:59997)"
level=INFO ts=2022-01-27T11:00:04.568091574Z app=device-opcua source=messaging.go:69 msg="Setting options for secure MessageBus with AuthMode='usernamepassword' and SecretName='redisdb"
level=INFO ts=2022-01-27T11:00:04.56968194Z app=device-opcua source=messaging.go:99 msg="Connected to redis Message Bus @ redis://localhost:6379 publishing on 'edgex/events/device' prefix topic with AuthMode='usernamepassword'"
level=INFO ts=2022-01-27T11:00:04.570360547Z app=device-opcua source=init.go:137 msg="Check core-metadata service's status by ping..."
level=INFO ts=2022-01-27T11:00:04.571719401Z app=device-opcua source=init.go:56 msg="Service clients initialize successful."
level=INFO ts=2022-01-27T11:00:04.572147996Z app=device-opcua source=restrouter.go:47 msg="Registering v2 routes..."
level=INFO ts=2022-01-27T11:00:04.577399704Z app=device-opcua source=config.go:223 msg="Skipping use of Configuration Provider for custom configuration: Provider not available"
level=INFO ts=2022-01-27T11:00:04.578539535Z app=device-opcua source=config.go:373 msg="Loaded custom configuration from ./res/configuration.toml"
level=INFO ts=2022-01-27T11:00:04.579070217Z app=device-opcua source=config.go:282 msg="Loaded custom configuration from file (0 envVars overrides applied)"
level=DEBUG ts=2022-01-27T11:00:04.579391199Z app=device-opcua source=driver.go:63 msg="Custom config is: &{{SimulationServer None None   {Counter,Random}}}"
level=WARN ts=2022-01-27T11:00:04.57966382Z app=device-opcua source=config.go:295 msg="unable to watch custom configuration for changes: Configuration Provider not enabled"
level=DEBUG ts=2022-01-27T11:00:04.579935829Z app=device-opcua source=service.go:198 msg="trying to find device service device-opcua"
level=INFO ts=2022-01-27T11:00:04.580941665Z app=device-opcua source=service.go:216 msg="device service device-opcua exists, updating it"
level=INFO ts=2022-01-27T11:00:04.584254944Z app=device-opcua source=profiles.go:54 msg="Loading pre-defined profiles from /home/sawashar/ireland/device-opcua-go-main/cmd/res/profiles"
level=INFO ts=2022-01-27T11:00:04.586400379Z app=device-opcua source=profiles.go:88 msg="Profile OPCUA-Server exists, using the existing one"
level=INFO ts=2022-01-27T11:00:04.586885915Z app=device-opcua source=devices.go:49 msg="Loading pre-defined devices from /home/sawashar/ireland/device-opcua-go-main/cmd/res/devices"
level=INFO ts=2022-01-27T11:00:04.587216643Z app=device-opcua source=devices.go:85 msg="Device SimulationServer exists, using the existing one"
0s
level=INFO ts=2022-01-27T11:00:04.587864262Z app=device-opcua source=autodiscovery.go:39 msg="AutoDiscovery stopped: interval error in configuration"
level=INFO ts=2022-01-27T11:00:04.588122482Z app=device-opcua source=autodiscovery.go:43 msg="AutoDiscovery stopped: ProtocolDiscovery not implemented"
level=INFO ts=2022-01-27T11:00:04.588359389Z app=device-opcua source=message.go:50 msg="Service dependencies resolved..."
level=INFO ts=2022-01-27T11:00:04.588705859Z app=device-opcua source=message.go:51 msg="Starting device-opcua 0.0.0 "
level=INFO ts=2022-01-27T11:00:04.588966897Z app=device-opcua source=message.go:55 msg="device opcua started"
level=INFO ts=2022-01-27T11:00:04.589212602Z app=device-opcua source=message.go:58 msg="Service started in: 24.475597ms"

Seems like Autodiscovery has stopped and now it not reading any value from server. Can you please help.

**Comment by jrtitus** [comment]
AutoDiscovery is not necessary to read values. As of now, it is not implemented in this service because the driver does not implement `func (d *Driver) Discover()`.

Can you post your configuration?

**Comment by sawashar** [comment]
Hi,
Okay Thanks. So now the issue is why device service is not getting the values of attributes from OPCUA Server. I am following the same tutorial mentioned in ReadME with default onboarded device and default profile. Following is my configuration.toml and device.toml
[configuration.txt](https://github.com/edgexfoundry-holding/device-opcua-go/files/7957034/configuration.txt)
[device.txt](https://github.com/edgexfoundry-holding/device-opcua-go/files/7957054/device.txt)
Thanks in advance.

**Comment by jrtitus** [comment]
Well, this is interesting.. 🤔 

On one hand, I'm unable to reproduce your issue if I run the service in a container as part of the EdgeX docker-compose file. By tailing the docker log for the device-opcua container I can see values being read matching the values coming from Prosys.

To the end of the `services` section of [this file](https://github.com/edgexfoundry/edgex-compose/blob/jakarta/docker-compose-no-secty.yml) I added the following:

```yml
  device-opcua:
    container_name: edgex-device-opcua
    depends_on:
    - consul
    - data
    - metadata
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_HOST: edgex-redis
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-device-opcua
    hostname: edgex-device-opcua
    image: edgexfoundry/device-opcua-go:0.0.0-dev
    networks:
      edgex-network: {}
    ports:
    - 127.0.0.1:59997:59997/tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
```

On the other hand, I **_am_** able to reproduce your issue if I build and run the device-opcua executable while other EdgeX Foundry components are running as containers. Unfortunately I'm not entirely sure why...

Is that how you're running the services as well?
